config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: {
  #   omniauth_callbacks: 'users/omniauth_callbacks'
  # }
  
  root to: 'books#index'
  resources :books do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show]
  resources :tags, param: :tag, only: [:show]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :tags

  validates :title,   presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 250 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :book

  validates :tag, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name,     presence: true
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 8 }

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        name: auth.info.name,
        nickname: auth.info.nickname,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end



  def self.guest
    user = find_or_create_by!(name: "test", nickname: "guest_user", email: 'guest_user@examaple.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "ログアウトしました"
    books_path
  end

  def after_sign_in_path_for(resource)
    if current_user
      flash[:notice] = "ログインしました" 
      books_path
    else
      flash[:notice] = "新規登録完了しました。"
      books_path
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :redirect_root, only: [:new, :edit]
  include Pagy::Backend
  
  def index
    @pagy, @books = pagy(Book.all.includes(:user).order("created_at DESC"))
    @tags = Tag.includes(:book).group(:tag).pluck(:book_id)
    @book_tags = Book.find(@tags)
  end

  def new
    @book = Book.new
    @book.tags.build
  end

  def create
    @book = current_user.books.create(book_params)
    if @book.save
      flash[:notice] = "投稿しました"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      if @book.update(book_params)
        flash[:notice] = "投稿を更新しました"
        redirect_to root_path
      else
        render :edit
      end
    else
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.user_id == current_user.id
      if book.destroy
        flash[:notice] = "投稿を削除しました"
        redirect_to root_path
      else
        render :index
      end
    else
      redirect_to root_path
    end
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments.includes(:user)
    @comment = Comment.new
  end

  private
  def book_params
    params.require(:book).permit( :title, :content, tags_attributes: [:id, :book_id, :tag])
  end

  def redirect_root
    redirect_to root_path unless user_signed_in?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(content: comment_params[:content], book_id: comment_params[:book_id], user_id: current_user.id)
    if @comment.content.blank?
      redirect_to root_path
    else
      respond_to do |format|
        format.html { redirect_to book_path(params[:book_id]), notice: 'コメントが投稿されました' }
        format.json 
      end
    end
  end

  def destroy
    if Comment.find_by(id: params[:id], book_id: params[:book_id]).destroy
      flash[:notice] = "コメントを削除しました"
      redirect_to book_path(params[:book_id])
    else
      redirect_to root_path
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :book_id).merge(book_id: params[:book_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tags = Tag.where(tag: params[:tag]).pluck(:book_id)
    @books = Book.find(@tags)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Twitter'
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_path
    end
  end

  def after_sign_in_path_for(resource)
    if @user.id == nil
      new_user_registration_path
    else
      root_path
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # def new
  #   session.delete('devise.omniauth_data')
  #   super
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def show
    @books = current_user.books
  end
  private

  def require_login
    unless user_signed_in?
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_header.erb
<!-- bookログを含んだヘッダー。トップページのみに使用!-->
<%= javascript_include_tag 'turn.js' %>

<!-- ヘッダー -->
<div class="top">
  <header class="top__header">
    <div class="top__header--logo">

      <section>

        <!-- フラッシュ -->
        <%= render "layouts/flash" %>

        <!-- 本をめくる -->
          <div id="flipbook">
            <% (1..100).each do |i| %>
              <% if i == 1 %>
                <span class="book__title"><span class="page-turn-over">ページをめくってね！</span></span>
              <% elsif i == 100 %>
                <%= image_tag 'book_back.jpg' %>
              <% else %>
                <div>
                  <img src="<%= "https://picsum.photos/460/582?grayscale&/?random/image=" + "#{i}" %>">
                </div>
              <% end %>
            <% end %>
          </div>

          <!-- スライダーでタグ一覧を表示 -->
          <div class="slider-head">＜タグ一覧＞</div>
            <div class="slider">
              <% @book_tags.each do |book| %>
                <span class="chip content">
                  <% book.tags.each do |t| %>
                    <%= link_to t.tag, tag_path(t.tag) %>
                  <% end %>
                </span>
              <% end %>
            </div>

      </section>
    </div>

    <!-- サイドのヘッダー -->
    <%= render "left_header" %>

  </header>
</div>

app/views/books/_index.html.erb
<!-- 投稿要素詳細 -->

<% @books.each do |book| %>
<div class="top__main__contents">
  <div class="top__main__contents__glid">

    <div class="top__main__contents__glid__header">
      <div class="top__main__contents__glid__header--title">
        <span>タイトル： </span><%= book.title %>
      </div>
        <div class="top__main__contents__glid__header__others">

          <ul class="top__main__contents__glid__header__others__ul">
            <li class="top__main__contents__glid__header__others__ul--li">
              <span class="chip content">
                <% book.tags.each do |t| %>
                  <%= link_to t.tag, tag_path(t.tag) %>
                <% end %>
              </span>
            </li>

            <li class="top__main__contents__glid__header__others__ul--li2">
              <i class="fas fa-angle-down"></i>
                <ul class="top__main__contents__glid__header__others__ul--ul">
                
                  <li class="top__main__contents__glid__header__others__ul--ul--li">
                    <% if user_signed_in? && current_user.id == book.user_id %>
                      <span><%= link_to "編集", "/books/#{book.id}/edit" %></span>
                    <% end %>
                  </li>
                  
                  <li class="top__main__contents__glid__header__others__ul--ul--li">
                    <span><%= link_to "詳細", "/books/#{book.id}" %></span>
                  </li>

                  <li class="top__main__contents__glid__header__others__ul--ul--li">
                    <% if user_signed_in? && current_user.id == book.user_id %>
                      <span><%= link_to '削除', "/books/#{book.id}", method: :delete %></span>
                    <% end %>
                  </li>
                </ul>
            </li>
          </ul>

        </div>
    </div>

    <div class="top__main__contents__glid__text">
      <div class="top__main__contents__glid__text--content">
        <span>内容： </span><%= book.content %>
      </div>
    </div>

    <div class="top__main__contents__glid__footer">
      <div class="top__main__contents__glid__footer--time">
        <span>投稿日時： </span><%= book.created_at.strftime("%Y/%m/%d %H:%M") %>
      </div>
      <div class="top__main__contents__glid__footer--name">
        <span>名前： </span><%= book.user.nickname %>
      </div>
    </div>
    <div class="top__main__contents__glid__footer--comment">
      <% book.comments.each do |c| %>
        <% if c.content %>
          <i><%= link_to "コメントあり", "/books/#{book.id}" %></i>
          <% break %>
        <% end %>
      <% end %>
    </div>

  </div>
</div>
<% end %>

app/views/books/_left_header.erb
<!-- サイドのヘッダー -->
<div class="top">
  <header class="top__header">
      <div class="top__header__menu">
        <ul class="top__header__menu--ul">

          <li class="top__header__menu--list1">
            <span class="top__header__menu--figure1"><%= link_to "積読スッキリ!!", "/", class: "top__header__menu--link" %></span>
            <%= image_tag 'menu_title.png', class: "top__header__menu--img" %>
          </li>

          <li class="top__header__menu--list2">
            <% if user_signed_in? %>
              <% if controller.controller_name == 'users' && controller.action_name == 'show' %>
                <span class="top__header__menu--figure2 edit__user">
                  <%= link_to "ユーザー編集", "/users/edit", class: "top__header__menu--link" %>
                </span>
              <% else %>
                <span class="top__header__menu--figure2">
                  <%= link_to "マイページ", "/users/#{current_user.id}", class: "top__header__menu--link" %>
                </span>
              <% end %>
            <% else %>
              <span class="top__header__menu--figure2">
                <%= link_to "新規登録", new_user_registration_path, class: "top__header__menu--link" %>
              </span>
            <% end %>
            <%= image_tag 'signup-mypage.png', class: "top__header__menu--img" %>
          </li>

          <li class="top__header__menu--list3">
            <% if user_signed_in? %>
              <span class="top__header__menu--figure3">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "top__header__menu--link" %>
              </span>
            <% else %>
              <span class="top__header__menu--figure3">
                <%= link_to "ログイン", new_user_session_path, class: "top__header__menu--link" %>
              </span>
            <% end %>
            <%= image_tag 'signin-signout.png', class: "top__header__menu--img" %>
          </li>

          <li class="top__header__menu--list4">
            <span class="top__header__menu--figure4"><%= link_to "投稿する", new_book_path, class: "top__header__menu--link" %></span>
            <%= image_tag 'toukou.png', class: "top__header__menu--img" %>
          </li>

          <% unless user_signed_in? %>
            <li class="top__header__menu--list5">
              <span class="top__header__menu--figure5">
                <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "top__header__menu--link" %>
              </span>
              <%= image_tag 'guest.png', class: "top__header__menu--img" %>
            </li>
          <% end %>

        </ul>
      </div>
  </header>
</div>


<!-- サイドのハンバーガーメニュー ヘッダー -->
<div class="ham-content">
  <input type="checkbox" id="togglenav">
  <label for="togglenav" class="togglenav-btn"></label>
  <label for="togglenav" class="togglenav-bg"></label>

  <nav class="drawer">
    <ul class="drawer__menu">

      <li class="drawer__menu--item">
        <%= link_to "積読スッキリ!!", "/" %>
      </li>

      <li class="drawer__menu--item">
        <% if user_signed_in? %>
          <% if controller.controller_name == 'users' && controller.action_name == 'show' %>
              <%= link_to "ユーザー編集", "/users/edit" %>
          <% else %>
              <%= link_to "マイページ", "/users/#{current_user.id}" %>
          <% end %>
        <% else %>
            <%= link_to "新規登録", new_user_registration_path %>
        <% end %>
      </li>

      <li class="drawer__menu--item">
        <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "ログイン", new_user_session_path %>
        <% end %>
      </li>

      <li class="drawer__menu--item">
        <%= link_to "投稿する", new_book_path %>
      </li>

      <% unless user_signed_in? %>
        <li class="drawer__menu--item">
          <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %>
        </li>
      <% end %>

    </ul>
  </nav>
</div>

app/views/books/edit.html.erb
<!-- サイドのヘッダー -->
<%= render "left_header" %>

<!-- 編集画面 -->
<div class="edit">
  <div class="edit__container">
    <h1 class="edit__container--header">編集する</h1>

      <div class="edit__container__contents">

      <!-- エラーメッセージ -->
      <%= render "layouts/post_error_message" %>

        <%= form_for(@book) do |form| %>

          <div class="edit__container__contents__field">
            <%= form.label :id, "投稿ID"  %>
            <%= form.text_field :id, readonly:"readonly" %>
          </div>

          <div class="edit__container__contents__field">
            <%= form.label :title, "タイトル" %><em class="edit__letter__limit">(30文字まで)</em>
            <%= form.text_field :title %>
          </div>

          <div class="edit__container__contents__field--content">
            <%= form.label :content, "内容" %><em class="edit__letter__limit">(250文字まで)</em>
            <p><%= form.text_area :content, id: "input-text" %></p>
            <p id="counter", class="edit__container__contents__field--count">現在の入力文字数：0文字</p>
          </div>

            <%= form.fields_for :tags do |tag__form| %>
                <div class="edit__container__contents__field">
                  <%= tag__form.label :tag, "タグ" %><em class="edit__letter__limit">(10文字まで)</em>
                    <%= tag__form.text_field :tag %>
              </div>
            <% end %>
          <div class="edit__container__contents__submit">
          <%= form.submit "更新する", class:"edit__container__contents__submit--button" %></div>
        <% end %>
      </div>

  </div>
</div>

app/views/books/index.html.erb
<!-- ポップ表示 -->
<div class="containers">
  <div class="containers__neumo"></div>
    <div class="containers__neumo__card containers__neumo__active">
      <p class="containers__neumo__card--title">「積読スッキリ！！」とは・・・</p>
      <div class="containers__neumo__card--detail">
        <p>・本をアウトプットするという記録用ログ</p>
        <p>・本の内容について交流できるコミュニケーションツール</p>
      </div>
      <p class="containers__neumo__card--assist">是非、読書をインプットからアウトプットへとシフトしてみてください！！</p>
      <p><button class="containers__neumo__card--button">閉じる</button></p>
    </div>
</div>

<!-- ヘッダー -->
<%= render "header" %>

  <!-- 投稿要素ヘッダー -->
  <div class="top__main">
    <section class="top__main--section">
      <h5 class="top__main--title"></h5>
      <h3 class="top__main--detail">Read Books</h3>

        <!-- 投稿要素詳細 -->
        <%= render "index" %>

      <%== pagy_nav(@pagy) %>
    </section>
  </div>

  <!-- フッダー -->
  <footer class="top__footer">
  <small class="top__footer__copyright">Copyright&copy; <a href="index.html">T.U.</a></small>
  <p class="top__footer__jump"><a href="#">🔝</a></p>
  </footer>

app/views/books/new.html.erb
<!-- サイドのヘッダー -->
<%= render "left_header" %>

<!-- 新規投稿 -->
<div class="new">
  <div class="new__container">
    <h1 class="new__container--header">投稿する</h1>
      <div class="new__container__contents">

      <!-- エラーメッセージ -->
      <%= render "layouts/post_error_message" %>

        <%= form_for(@book) do |form| %>

          <div class="new__container__contents__field">
            <%= form.label :title, "タイトル" %><em class="new__letter__limit">(30文字まで)</em>
            <%= form.text_field :title %>
          </div>

          <div class="new__container__contents__field--content">
            <%= form.label :content, "内容" %><em class="new__letter__limit">(250文字まで)</em>
            <p><%= form.text_area :content, id: "input-text" %></p>
            <p id="counter", class="new__container__contents__field--count">現在の入力文字数：0文字</p>
          </div>

            <%= form.fields_for :tags do |tag__form| %>
                <div class="new__container__contents__field">
                  <%= tag__form.label :tag, "タグ" %><em class="new__letter__limit">(10文字まで)</em>
                    <%= tag__form.text_field :tag %>
              </div>
            <% end %>
          <div class="new__container__contents__submit">
          <%= form.submit "送信する", class:"new__container__contents__submit--button" %></div>
        <% end %>
      </div>

  </div>
</div>

app/views/books/show.html.erb
<!-- サイドのヘッダー -->
<%= render "left_header" %>

<!-- 投稿した詳細画面 -->
<div class="top__main">
  <section class="top__main--section">

  <!-- フラッシュ -->
  <%= render "layouts/flash" %>

    <h2 class="top__main--title">Read Book(詳細)</h2>

      <div class="top__main__contents">
        <div class="top__main__contents__glid">

          <div class="top__main__contents__glid__header">
            <div class="top__main__contents__glid__header--title">
              <span>タイトル： </span><%= @book.title %>
            </div>
              <div class="top__main__contents__glid__header__others">

                <ul class="top__main__contents__glid__header__others__ul">
                  <li class="top__main__contents__glid__header__others__ul--li">
                    <span class="chip content">
                      <% @book.tags.each do |t| %>
                        <%= t.tag %>
                      <% end %>
                    </span>
                  </li>

                  <li class="top__main__contents__glid__header__others__ul--li2">
                    <% if user_signed_in? && current_user.id == @book.user_id %>
                      <i class="fas fa-angle-down"></i>
                        <ul class="top__main__contents__glid__header__others__ul--ul">
                          <li class="top__main__contents__glid__header__others__ul--ul--li">
                            <span><%= link_to "編集", "/books/#{@book.id}/edit" %></span>
                          </li>
                          <li class="top__main__contents__glid__header__others__ul--ul--li">
                            <span><%= link_to '削除', "/books/#{@book.id}", method: :delete %></span>
                          </li>
                        </ul>
                    <% end %>
                  </li>
                </ul>

              </div>
          </div>

          <div class="top__main__contents__glid__text">
            <div class="top__main__contents__glid__text--content">
              <span>内容： </span><%= @book.content %>
            </div>
          </div>

          <div class="top__main__contents__glid__footer">
            <div class="top__main__contents__glid__footer--time">
              <span>投稿日時： </span><%= @book.created_at.strftime("%Y/%m/%d %H:%M") %>
            </div>
            <div class="top__main__contents__glid__footer--name">
              <span>名前： </span><%= @book.user.nickname %>
            </div>
          </div>

        </div>
      </div>

  <!-- コメント -->
  <% if current_user %>
    <div class="comment__posts">
      <%= form_for [@book, @comment], id: "new_comment" do |form| %>
        <div class="comment__posts__field">
          <%= form.label :content, "コメント" %>
          <%= form.text_area :content, class: "textbox" %>
          <div class="comment__posts__submit">
            <%= form.submit "送信する", class:"comment__posts__submit--button" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

    <div class="comment__list">
      <h6 class="comment__list--header">＜コメント一覧＞</h6>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="comment__list__element">
            <strong class="comment__list__element--nickname">
              <%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：
            </strong>
            <span class="comment__list__element--comment"><%= comment.content %></span>
              <% if user_signed_in? && current_user.id == comment.user_id %>
                <p class="comment__list__element--link">
                  <%=link_to "削除", book_comment_path(comment.book.id, comment.id), method: :delete %>
                </p>
              <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  </section>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="time-limit">
    <%= flash[:notice] %>
  </p>
<% end %>

app/views/layouts/_post_error_message.html.erb
<% if @book.errors.any? %>
  <div class="alert-warning">
    <ul>
      <% @book.errors.full_messages_for(:title).each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @book.errors.any? %>
  <div class="alert-warning">
    <ul>
      <% @book.errors.full_messages_for(:content).each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @book.errors.any? %>
  <div class="alert-warning">
    <ul>
      <% @book.errors.full_messages_for(:"tags.tag").each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>積読スッキリ!!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
  </head>

  <body>
  
    <%= yield %>

  </body>
</html>

app/views/tags/show.html.erb
<!-- サイドのヘッダー -->
<%= render "books/left_header" %>

  <!-- 同じタグでソートした投稿一覧 -->
  <div class="top__main">
    <section class="top__main--section">
    <h3 class="top__main--title">「
      <% @books.each do |book| %>
        <% book.tags.each do |t| %>
          <%= t.tag[0] %>
        <% end %>
      <% end %>
      」タグ一覧
    </h3>

        <%= render "books/index" %>

    </section>
  </div>

  <footer class="top__footer">
  <small class="top__footer__copyright">Copyright&copy; <a href="index.html">T.U.</a></small>
  <p class="top__footer__jump"><a href="#">🔝</a></p>
  </footer>

app/views/users/show.html.erb
<!-- サイドのヘッダー -->
<%= render "books/left_header" %>

  <!-- ユーザーマイページ -->
  <div class="top__main">
    <section class="top__main--section">
      <h3 class="top__main--title">マイページ</h3>

        <%= render "books/index" %>

    </section>
  </div>

  <footer class="top__footer">
  <small class="top__footer__copyright">Copyright&copy; <a href="index.html">T.U.</a></small>
  <p class="top__footer__jump"><a href="#">🔝</a></p>
  </footer>